### ISSUE TITLE
Develop api utils for getCdnPlusPurgeHistoryList

### ISSUE THREAD

**Issue by homubee** [homubee/Ncloud-CdnPurger#15]
### Issue Description

CDN purge 이력 확인 API(getCdnPlusPurgeHistoryList) 연결용 유틸리티 클래스 개발

### TODO

- [x] 유틸리티 클래스 개발
- [x] 테스트 코드 작성
- [x] UI와 기능 연결

### ETC.

특이사항 없음
