### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by homubee** [homubee/Ncloud-CdnPurger#17]
### Issue Description

버그 수정 및 ui 개선

### TODO

- [x] 단축키 관련 문제 수정
- [x] MessageDialog 창 타이틀 개선
- [x] 테이블 ui 세부 개선
- [x] API response용 DTO 클래스 추가
- [x] 기타 버그 및 개선사항 작업

### ETC.

특이사항 없음
