### ISSUE TITLE
Advance ui features

### ISSUE THREAD

**Issue by homubee** [homubee/Ncloud-CdnPurger#3]
### Issue Description

UI 관련 기능 개선 사항 반영

### TODO

- [x] MessageDialog 줄바꿈 방식 개선
- [x] MessageDialog 추가 활용
- [x] Dialog 상위 클래스 작성
- [x] Dialog 창 생성 위치 가운데 정렬
- [x] Status bar 내용 개선
- [x] UI 컴포넌트 이름 변경

### ETC.

특이사항 없음
