### ISSUE TITLE
Advanced menubar

### ISSUE THREAD

**Issue by homubee** [homubee/Ncloud-CdnPurger#5]
### Issue Description

메뉴바 내용 추가 및 개선

### TODO

- [x] 메뉴 이름 변경(영문, 단축키 고려)
- [x] Setting 메뉴 추가
- [x] Window 메뉴 추가
- [x] Help 메뉴 추가
- [x] 메뉴 단축키 추가
- [x] 메뉴별 기능 추가

### ETC.

특이사항 없음
