### ISSUE TITLE
Review code and refactor

### ISSUE THREAD

**Issue by homubee** [homubee/Ncloud-CdnPurger#7]
### Issue Description

코드 전반 검토 후 리팩토링

### TODO

- [x] 코드 검토
- [x] 파이썬 스타일 적용
- [x] 예외 처리 로직 개선
- [x] 중복 코드 제거
- [x] 기타 리팩토링

### ETC.

특이사항 없음
