### ISSUE TITLE
Add test code

### ISSUE THREAD

**Issue by homubee** [homubee/Ncloud-CdnPurger#9]
### Issue Description

테스트 코드 추가 및 단위 테스트 수행

### TODO

- [x] 프로젝트 구조 개편 (테스트 코드 폴더 생성)
- [x] 기능사항별 단위 테스트 코드 작성
- [x] 테스트 수행
- [x] 테스트 실패한 기능 개선

### ETC.

특이사항 없음
